### PR TITLE
add Priority for connectqueue

### PR DESCRIPTION
**Pull request by darknight2590**

### CODE REVIEW

**Comment by ihyajb** [comment]
we dont use `QBCore.Functions.ExecuteSql` anymore.... we havent for a while

**Review by ghost — CHANGES_REQUESTED** [review]
You will have to make change based from [this](https://github.com/qbcore-framework/connectqueue/pull/1#issuecomment-921300914) since is not used anymore.

**Comment by darknight2590** [comment]
I just gave you the code that doesn't exist

**Review by zfbx — CHANGES_REQUESTED** [review]
needs porting to oxmysql

**Comment by ghost** [comment]
Why don't you use the same table has users use by QBCore and just add the `priority`

**Comment by darknight2590** [comment]
Why was this Pull requests closed?

**Comment by ghost** [comment]
He close all my PR's too without any comments.

**Comment by darknight2590** [comment]
I have a server and I can't give priority access to anyone, even server developers and admin if the server is full

**Comment by zfbx** [comment]
hate to cross promote but I hope to have this sort of.. well actually this entire resource's purpose merged into zdiscord xD with prios based on role

**Comment by darknight2590** [comment]
Not tested

**Pull request closed without merging**
